In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/creditcard.csv')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [3]:
df = df.drop(columns=['Time'])
df.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0  0.098698  0.363787  0.090794  ... -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425 -0.166974  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  0.207643  ...  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024 -0.054952  ... -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  0.753074  ... -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 30 columns]

In [104]:
df['Amount'] = (df['Amount'] - np.mean(df['Amount'])) / np.std(df['Amount'])
df.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0  0.098698  0.363787  0.090794  ... -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425 -0.166974  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  0.207643  ...  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024 -0.054952  ... -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  0.753074  ... -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28    Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  0.244964      0  
1  0.167170  0.125895 -0.008983  0.014724 -0.342475      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  1.160686      0  
3  0.647376 -0.221929  0.062723  0.061458  0.140534      0  
4 -0.206010  0.502292  0.219422  0.215153 -0.073403      0  

[5 rows x 30 columns]

In [105]:
df.Class = df.Class.astype('category')
df.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0  0.098698  0.363787  0.090794  ... -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425 -0.166974  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  0.207643  ...  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024 -0.054952  ... -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  0.753074  ... -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28    Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  0.244964      0  
1  0.167170  0.125895 -0.008983  0.014724 -0.342475      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  1.160686      0  
3  0.647376 -0.221929  0.062723  0.061458  0.140534      0  
4 -0.206010  0.502292  0.219422  0.215153 -0.073403      0  

[5 rows x 30 columns]

In [106]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [107]:
492 / 284000

0.0017323943661971832

In [108]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=0, ratio=0.05)

x = df.loc[:,df.columns != 'Class']
y = df.loc[:,'Class']

x_train, y_train = smote.fit_sample(x, y)
x_train.shape

(298530, 29)

In [109]:
(y_train == 1).sum()

14215

In [110]:
from imblearn.under_sampling import RandomUnderSampler

sampler = RandomUnderSampler(random_state=0)
x_train, y_train = sampler.fit_resample(x_train, y_train)
x_train.shape

(28430, 29)

## Add noise

In [111]:
mu, sigma = 0, 2.5
noise = np.random.normal(mu, sigma, x_train.shape)
x_train += noise

In [112]:
(y_train == 0).sum(), (y_train == 1).sum()

(14215, 14215)

## Some tests

In [113]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

tree = DecisionTreeClassifier(random_state=0)

cross_val_score(tree, x_train, y_train, cv = 10, scoring='accuracy')

array([0.82876231, 0.84353024, 0.83825598, 0.83438819, 0.84353024,
       0.83638283, 0.83743842, 0.84025334, 0.83216045, 0.83919775])

In [97]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=0, n_estimators=10)
cross_val_score(rf, x_train, y_train, cv=10, scoring='accuracy')

array([0.92657343, 0.83450704, 0.91549296, 0.83450704, 0.86267606,
       0.8556338 , 0.8943662 , 0.89084507, 0.89788732, 0.86267606])

In [98]:
x_train.shape

(2842, 29)

In [114]:
df = pd.DataFrame.from_records(x_train)
df['label'] = y_train
df.head()

0         1         2         3         4         5         6  \
0  2.989884 -2.653221 -0.720699 -4.381233 -0.668097 -5.662155  5.358805   
1  2.227251 -0.284127 -0.835392 -0.533353 -2.368834 -0.658979 -2.237053   
2 -4.705499 -6.455636 -4.335879 -1.106584 -6.198845  9.868539  7.641525   
3 -2.449386 -2.080870  1.179249  1.501505 -2.189496  2.983790  2.456355   
4 -4.066825  2.094743 -0.875916  1.459035  0.776694  1.385534  4.067273   

          7         8         9  ...        20        21        22        23  \
0 -0.758994  0.810626 -1.089232  ... -3.248455 -3.432539 -1.891251  3.518097   
1 -3.448584 -2.457206  0.167674  ... -1.637147 -0.655915 -2.858788 -4.278352   
2  0.064660  1.167262 -4.871685  ... -2.611492 -1.247288  1.964126 -0.640483   
3  1.057319 -4.376563 -0.175150  ...  0.904318 -5.385998 -1.518671 -3.438959   
4  0.485723  1.562604 -0.125779  ... -0.998463 -0.981458  2.473883 -4.030788   

         24        25        26        27        28  label  
0 -1.225394 -1.158574  0.638857 -1.882054 -0.978363      0  
1  0.414946  4.392098  1.814025  2.738022 -4.445576      0  
2  5.255793  3.513110  2.622348 -0.293933  6.156797      0  
3 -1.599537 -1.778689 -0.837632  2.424525  0.731376      0  
4 -1.403318  0.203725  2.381356 -3.198258 -2.031521      0  

[5 rows x 30 columns]

In [115]:
df.to_csv('data/creditcardfraud.csv', index=False)

## Final export

In [1]:
import pandas as pd
import numpy as np

np.random.seed(0)

In [3]:
df = pd.read_csv('data/creditcard.csv')
df.head()

PCA1      PCA2      PCA3      PCA4      PCA5      PCA6      PCA7  \
0  6.459225  1.186582  0.739647  6.133001  4.829484 -3.891765  2.614531   
1  5.957488  3.642683 -1.140284  1.066453 -1.676292 -5.299979 -0.712560   
2 -3.989565 -4.949568 -1.311106 -1.900115 -7.740544  4.311965  3.778451   
3  3.154211  4.160147  3.770452 -1.901053 -3.260468  2.842510  0.593450   
4 -2.092206  4.513400 -2.369502  0.803814  6.067657  2.808724  1.972406   

       PCA8      PCA9     PCA10  ...       PCA21     PCA22     PCA23  \
0 -0.732004  0.376378  0.555106  ...   -6.184692  2.375187  2.151346   
1  0.161746  3.553725  3.052909  ...   -4.371242 -1.370783 -1.963494   
2 -3.947818  2.194275 -5.176124  ...   -0.805322 -0.251309  3.409881   
3  2.685667 -1.389667  2.694095  ...   -2.997891  4.097696 -0.392523   
4  2.727058  1.433499 -3.204466  ...   -1.677528  0.614178 -1.500013   

      PCA24     PCA25     PCA26     PCA27     PCA28   amount  label  
0 -1.940469  5.902771 -3.733206  0.113368 -0.500350     2.99      0  
1  1.016401 -1.433778 -2.745661 -0.142777  1.011820     1.98      0  
2 -0.950663 -1.879831  2.476560  0.677415 -3.646334  1937.66      0  
3 -2.437611  4.754191  3.010292  4.440267  2.107858   320.05      0  
4  2.359001  1.459275  0.090837  0.520071 -3.247023    11.50      0  

[5 rows x 30 columns]

In [46]:
df = df.drop(columns=['Time'])
df.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0  0.098698  0.363787  0.090794  ... -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425 -0.166974  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  0.207643  ...  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024 -0.054952  ... -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  0.753074  ... -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 30 columns]

In [47]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=0, ratio=0.05)

x = df.loc[:,df.columns != 'Class']
y = df.loc[:,'Class']

x_train, y_train = smote.fit_sample(x, y)
x_train.shape

(298530, 29)

In [48]:
from imblearn.under_sampling import RandomUnderSampler

sampler = RandomUnderSampler(random_state=0)
x_train, y_train = sampler.fit_resample(x_train, y_train)
x_train.shape

(28430, 29)

In [49]:
x_train[0]

array([ 2.04909444e+00,  1.86188932e-01, -1.70719812e+00,  5.30767935e-01,
        1.60588627e-01, -1.44856987e+00,  2.39309799e-01, -3.53611397e-01,
        6.34424823e-01, -4.71390439e-01, -3.49232573e-01, -7.34740026e-02,
       -3.03129963e-01, -6.64253651e-01,  9.77498573e-01,  1.57690917e-01,
        4.69860291e-01,  4.46847313e-01, -5.02305697e-01, -2.32666221e-01,
        1.97782313e-01,  7.41140605e-01, -9.74447269e-03, -8.50567690e-02,
        2.28384287e-01, -9.72920020e-02, -1.02843967e-03, -3.23903907e-02,
        2.99000000e+00])

In [50]:
mu, sigma = 0, 2.5
noise = np.random.normal(mu, sigma, (x_train.shape[0], x_train.shape[1] - 1))
x_train[:,:-1] += noise

In [51]:
x_train[0]

array([ 6.4592253 ,  1.18658195,  0.73964684,  6.13300093,  4.8294836 ,
       -3.89176456,  2.61453084, -0.73200442,  0.37637769,  0.55510582,
        0.01087635,  3.56220976,  1.59946435, -0.36006611,  2.08715666,
        0.99187673,  4.20505797, -0.06604835,  0.28036356, -2.36790557,
       -6.18469223,  2.37518709,  2.15134602, -1.94046932,  5.90277085,
       -3.73320619,  0.11336785, -0.50035002,  2.99      ])

In [56]:
df = pd.DataFrame.from_records(x_train)
df['label'] = y_train
df.columns = ['PCA{}'.format(_) for _ in range(1, 29)] + ['amount', 'label']
df.head()
df.to_csv('data/creditcardfraud.csv', index=False)

## Shuffling

In [8]:
df = pd.read_csv('data/creditcardfraud.csv')
df.head()

PCA1      PCA2      PCA3      PCA4      PCA5      PCA6      PCA7  \
0  6.459225  1.186582  0.739647  6.133001  4.829484 -3.891765  2.614531   
1  5.957488  3.642683 -1.140284  1.066453 -1.676292 -5.299979 -0.712560   
2 -3.989565 -4.949568 -1.311106 -1.900115 -7.740544  4.311965  3.778451   
3  3.154211  4.160147  3.770452 -1.901053 -3.260468  2.842510  0.593450   
4 -2.092206  4.513400 -2.369502  0.803814  6.067657  2.808724  1.972406   

       PCA8      PCA9     PCA10  ...       PCA21     PCA22     PCA23  \
0 -0.732004  0.376378  0.555106  ...   -6.184692  2.375187  2.151346   
1  0.161746  3.553725  3.052909  ...   -4.371242 -1.370783 -1.963494   
2 -3.947818  2.194275 -5.176124  ...   -0.805322 -0.251309  3.409881   
3  2.685667 -1.389667  2.694095  ...   -2.997891  4.097696 -0.392523   
4  2.727058  1.433499 -3.204466  ...   -1.677528  0.614178 -1.500013   

      PCA24     PCA25     PCA26     PCA27     PCA28   amount  label  
0 -1.940469  5.902771 -3.733206  0.113368 -0.500350     2.99      0  
1  1.016401 -1.433778 -2.745661 -0.142777  1.011820     1.98      0  
2 -0.950663 -1.879831  2.476560  0.677415 -3.646334  1937.66      0  
3 -2.437611  4.754191  3.010292  4.440267  2.107858   320.05      0  
4  2.359001  1.459275  0.090837  0.520071 -3.247023    11.50      0  

[5 rows x 30 columns]

In [9]:
df = df.sample(frac=1).reset_index(drop=True)

In [10]:
df.head()

PCA1       PCA2       PCA3       PCA4       PCA5      PCA6       PCA7  \
0 -17.728424  12.065210 -19.208018  10.364634 -15.394158  2.946509 -21.193947   
1 -11.764058  10.201160 -10.063689   4.750370 -16.151861 -0.692401 -14.866960   
2  -0.118736   5.127423   5.141188   2.981300  -4.726511  1.449841  -1.174396   
3  -2.400023   0.853067  -0.347057   6.537439  -7.072598 -0.730034   4.883411   
4   1.424880  -0.315770  -1.352672  -2.546808   1.097185 -1.685004  -0.614326   

       PCA8       PCA9      PCA10  ...       PCA21     PCA22     PCA23  \
0 -3.909177 -10.059195 -14.882112  ...   -9.171033 -0.928310  1.199864   
1  5.785251  -8.982269 -14.252734  ...   -3.070527 -0.963859 -1.264751   
2  2.524995   6.215809  -0.710249  ...   -1.551779  6.454845  4.041127   
3 -1.699163  -2.770298  -6.031566  ...    2.490629 -0.488862 -2.728449   
4  2.913067  -2.123813  -4.903598  ...    2.167195  3.153440 -2.479621   

      PCA24     PCA25     PCA26     PCA27     PCA28       amount  label  
0 -0.562050 -4.301500 -0.046673 -5.413858  2.120568     6.263980      1  
1  4.257839 -8.793458 -1.037544 -0.481525  0.660005     9.688198      1  
2 -5.385846 -2.965258  4.425672 -4.267967 -3.055587     2.610000      0  
3  1.597938 -0.283878  0.247595 -0.488089  1.349121  1366.258812      1  
4 -0.506374  1.460237 -2.087868 -1.853626  1.099593    45.000000      0  

[5 rows x 30 columns]

In [11]:
df.to_csv('data/creditcardfraud_shuffled.csv', index=False)